accounts/urls.py
from django.urls import path

from accounts.views import register

app_name = 'accounts'
urlpatterns = [
    path('register/', register, name='register'),
]

core/urls.py
from django.urls import path

from core.views import about, contact, home

app_name = 'core'
urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

services/urls.py
from django.urls import path

from services.views import create_order, create_review, detail, list

app_name = 'services'
urlpatterns = [
    path('', list, name='list'),
    path('<int:pk>/', detail, name='detail'),
    path('<int:pk>/order/', create_order, name='create_order'),
    path('review/<uuid:code>/', create_review, name='create_review'),
]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('services/', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Digite seu nome'})
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'placeholder': 'Digite seu email'})
    )
    phone = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={'placeholder': 'Digite seu telefone'}),
    )
    address = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': 'Digite seu endereço'}),
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Digite sua mensagem'})
    )

    def send_email(self):
        # Send email using the self.cleaned_data dictionary
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        phone = self.cleaned_data['phone']
        address = self.cleaned_data['address']
        message = self.cleaned_data['message']

        send_mail(
            f'Mensagem de {name} <{email}>',
            f'Telefone: {phone}\nEndereço: {address}\n\nMensagem: {message}',
            email,
            [settings.CONTACT_EMAIL],
        )

core/views.py
from django.db.models import Count
from django.shortcuts import render

from core.forms import ContactForm
from services.models import Service


def home(request):
    cities = (
        Service.objects.filter(user__profile__isnull=False)
        .values('user__profile__city')
        .distinct()
    )
    cities = [city['user__profile__city'] for city in cities]

    top_services = Service.objects.annotate(total_orders=Count('orders')).order_by(
        '-total_reviews'
    )[:3]

    return render(
        request, 'core/home.html', {'cities': cities, 'top_services': top_services}
    )


def about(request):
    return render(request, 'core/about.html')


def contact(request):
    form = ContactForm(request.POST or None)

    if form.is_valid():
        form.send_email()
        form = ContactForm()

    return render(request, 'core/contact.html', {'form': form})

core/templates/core/about.html
{% extends "base.html" %}

{% load static %}

{% block title %}Sobre{% endblock %}

{% block content %}
    <!-- info página -->
    <section class="pagina-info">
        <div class="container">
            <p>
                Sobre nós
            </p>
        </div>
    </section>

    <!-- Conheça sobre nós -->
    <section class="sobre">
        <div class="container">
            <sobre class="sobre-grid">
                <img src="https://www.sage.com/pt-pt/-/media/images/sagedotcom/master/partners/partners-partner-network-panel-3.png?h=520&iar=0&w=708&hash=7C06BB350224506E1972230C3D7DED9E" alt="Imagem ilustrativa"
                    width="100%">
                <div class="sobre-info">
                    <h2 class="sobre-titulo">
                        Conheça sobre nós
                    </h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                    <ul class="sobre-lista">
                        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod </li>
                        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod </li>
                        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod </li>
                        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod </li>
                    </ul>
                </div>
            </sobre>
        </div>
    </section>

    <section class="sobre-porque">
        {% include "fragments/_why_inner.html" %}
    </section>

    <!-- Comece como prestador -->
    <section class="prestador">
        <div class="container">
            <div class="prestador-grid">
                <div class="prestador-item">
                    <h2 class="prestador-titulo">
                        Comece como prestador
                    </h2>
                    <p class="prestador-descricao">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                    <ul>
                        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                        </li>
                        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                        </li>
                    </ul>
                    <a href="{% url "accounts:register" %}" class="btn-green">Seja um prestador</a>
                </div>
                <div class="prestador-item">
                    <img src="https://www.sage.com/pt-pt/-/media/images/sagedotcom/master/partners/partners-tech-panel-2.png?h=220&iar=0&w=464&hash=9CE94808CA38BC4AB1B08B7DAA5A62CE" alt=""
                        width="100%">
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

core/templates/core/contact.html
{% extends "base.html" %}

{% load static %}

{% block title %}Contato{% endblock %}

{% block content %}
    <main>
        <!-- info página -->
        <section class="pagina-info">
            <div class="container">
                <p>
                    Entre em contato com os nossos ninjas
                </p>
            </div>
        </section>
        
        <section class="contato">
            <div class="container">
                <div class="contato-grid">
                    <div class="contato-item">
                        <div class="contato-icone">
                            <img src="{% static 'img/icone-tel.svg' %}" alt="">
                        </div>
                        <h3>Contato telefônico</h3>
                        <p>
                            (11) 1234-5678<br>
                            (11) 9-1234-5678
                        </p>
                    </div>
                    <div class="contato-item">
                        <div class="contato-icone">
                            <img src="{% static 'img/icone-mail.svg' %}" alt="">
                        </div>
                        <h3>Contato por e-mail</h3>
                        <p>
                            contato@twninjas.com.br
                        </p>
                    </div>
                    <div class="contato-item">
                        <div class="contato-icone">
                            <img src="{% static 'img/icone-suporte.svg' %}" alt="">
                        </div>
                        <h3>Suporte ninja</h3>
                        <p>
                            Das 08:00h às 20:00h<br>
                            De segunda à sexta-feira
                        </p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Contato Form -->
        <section class="form-contato-secao">
            <div class="container">
                <h2>Entre em contato</h2>
                <div class="divisor-form">
                    <div class="status"></div>
                </div>
                <form class="form-contato" method="post">
                    {% csrf_token %}
                    <div class="form-item nome">
                        <label for="nome">Nome Completo*</label>
                        {{ form.name }}
                    </div>
                    <div class="form-item email">
                        <label for="email">E-mail*</label>
                        {{ form.email }}
                    </div>
                    <div class="form-item cel">
                        <label for="cel">Telefone celular*</label>
                        {{ form.phone }}
                    </div>
                    <div class="form-item endereco">
                        <label for="endereco">Endereço*</label>
                        {{ form.address }}
                    </div>
                    <div class="form-item mensagem">
                        <label for="mensagem">Mensagem*</label>
                        {{ form.message }}
                    </div>
                    <button type="submit" class="btn-green">ENVIAR MENSAGEM</button>
                </form>
            </div>
        </section>
    </main>
{% endblock %}

core/templates/core/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <!-- banner -->
  <section class="banner">
    <div class="container">
        <p class="banner-descricao">
            Contrate qualquer serviço, a qualquer momento e de qualquer lugar.
        </p>
        <h1 class="banner-titulo">
            SOLUÇÃO EM UM PASSO<br>
            PARA OS SEUS SERVIÇOS
        </h1>
        <form class="search-banner" method="get" action="{% url "services:list" %}">
            <select name="city" id="">
                <option value="" selected>Cidade</option>
                {% for city in cities %}
                    <option value="{{ city }}">{{ city }}</option>
                {% endfor %}
            </select>
            <div class="search-buttons">
                <label for="search">
                    <img src="{% static 'img/icon-search.svg' %}" alt="" width="20px">
                </label>
                <input type="text" name="q" id="search" placeholder="O que você está procurando...">
                <button type="submit">
                    <img src="{% static 'img/icone-right-arrow.svg' %}" alt="" width="25px">
                </button>
            </div>
        </form>
    </div>
  </section>

  <!-- Serviços -->
  <section class="home-servicos">
    <div class="container">
        <h2 class="servico-titulo">
            Serviços em destaque
        </h2>
        <p class="servico-descricao">
            É um fato estabelecido há muito tempo que um leitor se distrairá com o<br>
            conteúdo legível de uma página ao observar seu layout.
        </p>
        <div class="servicos-grid">
            {% for service in top_services %}
                <div class="servico-item">
                    <img src="{{ service.picture.url }}" alt="" width="100%"
                        class="img-destaque">
                    <div class="servico-body">
                        <div class="avatar">
                            <img src="{{ service.user.profile.avatar.url }}" alt="Foto prestador" width="45px" class="img-user">
                            <p>{{ service.user.get_full_name }}</p>
                        </div>
                        <h3>{{ service.name }}</h3>
                        <p>{{ service.description }}</p>
                        <a href="" class="servico-link">Iniciando em</a><span> ${{ service.price }}</span>
                        <a href="{% url "services:detail" pk=service.pk %}" class="servico-agendar">Ver detalhes</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
  </section>

  <!-- Porque -->
  <section class="porque">
    {% include "fragments/_why_inner.html" %}
  </section>
{% endblock content %}