accounts/urls.py
from django.urls import path

from accounts.views import register

app_name = 'accounts'
urlpatterns = [
    path('register/', register, name='register'),
]

core/urls.py
from django.urls import path

from core.views import about, contact, home

app_name = 'core'
urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

services/urls.py
from django.urls import path

from services.views import create_order, create_review, detail, list

app_name = 'services'
urlpatterns = [
    path('', list, name='list'),
    path('<int:pk>/', detail, name='detail'),
    path('<int:pk>/order/', create_order, name='create_order'),
    path('review/<uuid:code>/', create_review, name='create_review'),
]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('services/', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Digite seu nome'})
    )
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'placeholder': 'Digite seu email'})
    )
    phone = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={'placeholder': 'Digite seu telefone'}),
    )
    address = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'placeholder': 'Digite seu endereço'}),
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Digite sua mensagem'})
    )

    def send_email(self):
        # Send email using the self.cleaned_data dictionary
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        phone = self.cleaned_data['phone']
        address = self.cleaned_data['address']
        message = self.cleaned_data['message']

        send_mail(
            f'Mensagem de {name} <{email}>',
            f'Telefone: {phone}\nEndereço: {address}\n\nMensagem: {message}',
            email,
            [settings.CONTACT_EMAIL],
        )

core/views.py
from django.db.models import Count
from django.shortcuts import render

from core.forms import ContactForm
from services.models import Service


def home(request):
    cities = (
        Service.objects.filter(user__profile__isnull=False)
        .values('user__profile__city')
        .distinct()
    )
    cities = [city['user__profile__city'] for city in cities]

    top_services = Service.objects.annotate(total_orders=Count('orders')).order_by(
        '-total_reviews'
    )[:3]

    return render(
        request, 'core/home.html', {'cities': cities, 'top_services': top_services}
    )


def about(request):
    return render(request, 'core/about.html')


def contact(request):
    form = ContactForm(request.POST or None)

    if form.is_valid():
        form.send_email()
        form = ContactForm()

    return render(request, 'core/contact.html', {'form': form})

core/templates/fragments/_footer.html
{% load static %}

<footer class="footer">
  <div class="container">
      <div class="footer-grid">
          <img src="{% static 'img/twninjas-logo-claro.svg' %}" alt="" width="">
          <p>Todos os direitos reservados. (C) 2025</p>
      </div>
  </div>
</footer>

core/templates/fragments/_header.html
{% load static %}

<header class="header">
  <div class="container">
      <!-- Desktop -->
      <div class="menu-desktop">
          <a href="{% url 'core:home' %}"><img src="{% static 'img/twninjas-logo.svg' %}" alt="Logo TW Ninjas"></a>
          <nav>
              <ul>
                  <li>
                      <a href="{% url 'core:home' %}">
                          Home
                      </a>
                  </li>
                  <li>
                      <a href="{% url 'core:about' %}">
                          Sobre
                      </a>
                  </li>
                  <li>
                      <a href="{% url 'services:list' %}">
                          Lista de Serviços
                      </a>
                  </li>
                  <li>
                      <a href="{% url 'core:contact' %}">
                          Contato
                      </a>
                  </li>
                  <li>
                      <a class="btn-green" href="{% url 'accounts:register' %}" style="margin: 0;display: inline;">
                          Seja um prestador
                      </a>
                  </li>
              </ul>
          </nav>
      </div>

      <!-- mobile -->
      <div class="mobile">
      <div class="menu-mobile">
          <a href="{% url 'core:home' %}"><img src="{% static 'img/twninjas-logo.svg' %}" alt="Logo TW Ninjas"></a>
          <img src="{% static 'img/open-menu.svg' %}" alt="Logo TW Ninjas" width="30px" id="open-menu">

      </div>

      <div class="menu-hamburguer">
          <div class="header-hamburguer">
              <a href="{% url 'core:home' %}"><img src="{% static 'img/twninjas-logo.svg' %}" alt="Logo TW Ninjas"></a>
              <img src="{% static 'img/close-menu.svg' %}" alt="Logo TW Ninjas" width="30px" id="close-menu">
          </div>
          <nav>
              <ul>
                  <li>
                      <a href="{% url 'core:home' %}">
                          Home
                      </a>
                  </li>
                  <li>
                      <a href="{% url 'core:about' %}">
                          SObre
                      </a>
                  </li>
                  <li>
                      <a href="{% url 'services:list' %}">
                          Lista de Serviços
                      </a>
                  </li>
                  <li>
                      <a href="{% url 'core:contact' %}">
                          Contato
                      </a>
                  </li>
                  <li>
                      <a class="btn-green" href="{% url 'accounts:register' %}">
                          Seja um prestador
                      </a>
                  </li>
              </ul>
          </nav>
      </div>
      <div class="backdrop"></div>
      </div>
  </div>
</header>

core/templates/fragments/_why_inner.html
{% load static %}

<div class="container">
  <h2 class="porque-titulo">
      Por que nosso mercado?
  </h2>
  <p class="porque-descricao">
      É um fato estabelecido há muito tempo que um leitor se distrairá com o<br>
      conteúdo legível de uma página ao observar seu layout.
  </p>

  <div class="porque-grid">
      <div class="porque-item">
          <div class="porque-img">
              <img src="{% static 'img/icone-servico.svg' %}" alt="">
          </div>
          <h3 class="porque-servico-titulo">Service Commitment</h3>
          <p class="porque-servico-descricao">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>

      <div class="porque-item">
          <div class="porque-img">
              <img src="{% static 'img/icone-servico.svg' %}" alt="">
          </div>
          <h3 class="porque-servico-titulo">Service Commitment</h3>
          <p class="porque-servico-descricao">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>

      <div class="porque-item">
          <div class="porque-img">
              <img src="{% static 'img/icone-servico.svg' %}" alt="">
          </div>
          <h3 class="porque-servico-titulo">Service Commitment</h3>
          <p class="porque-servico-descricao">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>

      <div class="porque-item">
          <div class="porque-img">
              <img src="{% static 'img/icone-servico.svg' %}" alt="">
          </div>
          <h3 class="porque-servico-titulo">Service Commitment</h3>
          <p class="porque-servico-descricao">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>

      <div class="porque-item">
          <div class="porque-img">
              <img src="{% static 'img/icone-servico.svg' %}" alt="">
          </div>
          <h3 class="porque-servico-titulo">Service Commitment</h3>
          <p class="porque-servico-descricao">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>

      <div class="porque-item">
          <div class="porque-img">
              <img src="{% static 'img/icone-servico.svg' %}" alt="">
          </div>
          <h3 class="porque-servico-titulo">Service Commitment</h3>
          <p class="porque-servico-descricao">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
  </div>
</div>