core/urls.py
from django.urls import path

from core.views import about, contact, home

app_name = 'core'
urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

services/urls.py
from django.urls import path

from services.views import create_order, create_review, detail, list

app_name = 'services'
urlpatterns = [
    path('', list, name='list'),
    path('<int:pk>/', detail, name='detail'),
    path('<int:pk>/order/', create_order, name='create_order'),
    path('review/<uuid:code>/', create_review, name='create_review'),
]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('services/', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models


def service_upload_to(instance, filename):
    return f'services/{instance.user.username}/{filename}'


class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=9, decimal_places=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='services')
    picture = models.ImageField(upload_to=service_upload_to, blank=True, null=True)
    average_rating = models.DecimalField(
        max_digits=3, decimal_places=2, default=0, editable=False
    )
    total_reviews = models.PositiveIntegerField(default=0, editable=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'


class ServiceOrder(models.Model):
    class Status(models.TextChoices):
        OPEN = 'OPEN', 'Aberta'
        CANCELED = 'CANCELED', 'Cancelada'
        DONE = 'DONE', 'Concluída'
        FINISHED = 'FINISHED', 'Finalizada'

    code = models.UUIDField(default=uuid.uuid4, editable=False)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='orders')
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.TextField()
    extra_info = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=15, choices=Status.choices, default='OPEN')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.code)

    class Meta:
        verbose_name = 'Order Service'
        verbose_name_plural = 'Order Services'

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.service.user.email_user(
                subject='Nova ordem de serviço',
                message=f'Ordem de serviço: {self.code}\n\nNova ordem de serviço foi criada para o serviço: {self.service.name}',
            )

        return super().save(args, kwargs)


class ServiceOrderReview(models.Model):
    order = models.ForeignKey(
        ServiceOrder, on_delete=models.CASCADE, related_name='reviews'
    )
    rating = models.PositiveSmallIntegerField()
    comment = models.TextField()

    def __str__(self):
        return f'{self.order.code} - {self.rating}'

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

    def __notify_user(self):
        self.order.service.user.email_user(
            subject='Nova avaliação',
            message=f'Nova avaliação para o serviço: {self.order.service.name}\n\nComentário: {self.comment}',
        )

    def __update_service_order(self):
        self.order.status = ServiceOrder.Status.FINISHED
        self.order.save()

    def __update_service_rating(self):
        service = self.order.service
        service.total_reviews += 1
        service.average_rating = (
            service.average_rating + self.rating
        ) / service.total_reviews
        service.save()

    def __update_user_rating(self):
        user_profile = self.order.service.user.profile
        user_profile.total_reviews += 1
        user_profile.average_rating = (
            user_profile.average_rating + self.rating
        ) / user_profile.total_reviews
        user_profile.save()

    def save(self, *args, **kwargs):
        self.__notify_user()
        self.__update_service_order()
        self.__update_service_rating()
        self.__update_user_rating()

        return super().save(args, kwargs)

services/forms.py
from django import forms

from services.models import ServiceOrder, ServiceOrderReview


class ServiceOrderForm(forms.ModelForm):
    class Meta:
        model = ServiceOrder
        fields = ['service', 'name', 'email', 'phone', 'address', 'extra_info']
        widgets = {
            'address': forms.TextInput(),
            'service': forms.HiddenInput(),
        }


class ServiceOrderReviewForm(forms.ModelForm):
    class Meta:
        model = ServiceOrderReview
        fields = (
            'rating',
            'comment',
            'order',
        )
        widgets = {
            'rating': forms.HiddenInput(attrs={'id': 'rating-value'}),
            'order': forms.HiddenInput(),
            'comment': forms.Textarea(
                attrs={
                    'id': 'review-text',
                    'placeholder': 'Deixe seus comentários...',
                    'rows': 19,
                }
            ),
        }

services/views.py
from django.conf import settings
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from services.forms import ServiceOrderForm, ServiceOrderReviewForm
from services.models import Service, ServiceOrder, ServiceOrderReview
from services.utils import calculate_approval_rates


def list(request):
    query = request.GET.get('q', '')
    city = request.GET.get('city')

    services = Service.objects.filter(name__icontains=query)

    if city:
        services = services.filter(user__profile__city=city)

    paginator = Paginator(services, settings.PAGINATION)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    cities = (
        Service.objects.filter(user__profile__isnull=False)
        .values('user__profile__city')
        .distinct()
    )
    cities = [city['user__profile__city'] for city in cities]

    return render(request, 'services/list.html', {'page': page, 'cities': cities})


def detail(request, pk):
    service = get_object_or_404(Service, pk=pk)
    reviews = ServiceOrderReview.objects.filter(order__service=service)
    done_services = ServiceOrder.objects.filter(
        service=service,
        status__in=[ServiceOrder.Status.DONE, ServiceOrder.Status.FINISHED],
    ).count()

    user_done_services = ServiceOrder.objects.filter(
        service__user=service.user,
        status__in=[ServiceOrder.Status.DONE, ServiceOrder.Status.FINISHED],
    ).count()

    approval_rate = calculate_approval_rates(reviews)

    total_orders = ServiceOrder.objects.filter(service__user=service.user).count()

    conclusion_rate = (user_done_services / total_orders) * 100 if total_orders else 0

    return render(
        request,
        'services/detail.html',
        {
            'service': service,
            'reviews': reviews,
            'done_services': done_services,
            'user_done_services': user_done_services,
            'approval_rate': int(approval_rate),
            'conclusion_rate': int(conclusion_rate),
        },
    )


def create_order(request, pk):
    service = get_object_or_404(Service, pk=pk)
    form = ServiceOrderForm(request.POST or None, initial={'service': service})

    if form.is_valid():
        form.save()
        return redirect('services:detail', pk=pk)

    return render(
        request, 'services/create_order.html', {'service': service, 'form': form}
    )


def create_review(request, code):
    service_order = get_object_or_404(ServiceOrder, code=code)

    if service_order.status != ServiceOrder.Status.DONE:
        return redirect('services:detail', pk=service_order.service.pk)

    form = ServiceOrderReviewForm(request.POST or None, initial={'order': service_order})

    if form.is_valid():
        form.save()
        return redirect('services:detail', pk=service_order.service.pk)

    return render(
        request,
        'services/create_review.html',
        {'service_order': service_order, 'form': form},
    )

services/templates/services/create_order.html
{% extends "base.html" %}

{% block content %}
    <!-- info página -->
    <section class="pagina-info">
      <div class="container">
          <p>Solicitar Serviço - {{ service.name }}</p>
      </div>
  </section>

  <!-- Contato Form -->
  <section class="form-contato-secao">
      <div class="container">
          <h2>Informações de contratação</h2>
          <div class="divisor-form">
              <div class="status"></div>
          </div>
          <form class="form-contato" method='post'>
            {% csrf_token %}
            {{ form.service }}
            
            <div class="form-item nome">
                <label for="nome">Nome Completo*</label>
                {{ form.name }}
            </div>
            <div class="form-item email">
                <label for="email">E-mail*</label>
                {{ form.email }}
            </div>
            <div class="form-item cel">
                <label for="cel">Telefone celular*</label>
                {{ form.phone }}
            </div>
            <div class="form-item endereco">
                <label for="endereco">Endereco*</label>
                {{ form.address }}
            </div>
            <div class="form-item mensagem">
                <label for="solicitacao">Solicitação**</label>
                {{ form.extra_info }}
            </div>
            <button type="submit" class="btn-green">Registrar</button>
          </form>
      </div>
  </section>
{% endblock content %}

services/templates/services/create_review.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main>
  <!-- info página -->
  <section class="pagina-info">
    <div class="container">
        <p>Avaliar serviço - {{ service_order.service.name }}</p>
    </div>
  </section>
  <!-- Contato Form -->
  <section class="avaliacao">
    <div class="container">
      <h2>Avaliação</h2>
      <div class="divisor-form">
          <div class="status"></div>
      </div>
      <div class="avaliar-grid">
          <div class="avaliar-info">
              <img src="{{ service_order.service.picture.url }}" alt=""
                  width="100%">
              <div class="avaliar-bloco">
                  <img src="{{ service_order.service.user.profile.avatar.url }}" alt="" class="ft-usuario">
                  <h3>{{ service_order.service.user.get_full_name }}</h3>
              </div>
              <p>{{ service_order.service.description|linebreaksbr }}</p>
          </div>
          <form id="rating-form" method="post">
              {% csrf_token %}

              {{ form.order }}
              {{ form.comment }}
              {{ form.rating }}
              <div class="rating-buttom">
                  <div class="star-rating">
                      <img src="{% static "img/star-orange.svg" %}" alt="1 estrela" data-value="1">
                      <img src="{% static "img/star-orange.svg" %}" alt="2 estrelas" data-value="2">
                      <img src="{% static "img/star-orange.svg" %}" alt="3 estrelas" data-value="3">
                      <img src="{% static "img/star-orange.svg" %}" alt="4 estrelas" data-value="4">
                      <img src="{% static "img/star-orange.svg" %}" alt="5 estrelas" data-value="5">
                  </div>
                  <button class="btn-green" type="submit">Enviar Avaliação</button>
              </div>
          </form>
      </div>
    </div>
  </section>
</main>
{% endblock content %}

{% block scripts %}
<script>
  document.addEventListener('DOMContentLoaded', () => {
      const stars = document.querySelectorAll('.star-rating img');
      const ratingValue = document.getElementById('rating-value');
      let selectedRating = 0;

      stars.forEach((star, index) => {
          star.addEventListener('mouseover', () => {
              highlightStars(index);
          });

          star.addEventListener('click', () => {
              selectedRating = index + 1;
              ratingValue.value = selectedRating;
              setSelectedStars(selectedRating);
          });

          star.addEventListener('mouseout', () => {
              if (selectedRating > 0) {
                  setSelectedStars(selectedRating);
              } else {
                  resetStars();
              }
          });
      });

      function highlightStars(index) {
          resetStars();
          for (let i = 0; i <= index; i++) {
              stars[i].style.filter = 'none';
          }
      }

      function resetStars() {
          stars.forEach(star => {
              star.style.filter = 'grayscale(100%)';
              star.classList.remove('selected');
          });
      }

      function setSelectedStars(rating) {
          resetStars();
          for (let i = 0; i < rating; i++) {
              stars[i].classList.add('selected');
              stars[i].style.filter = 'none';
          }
      }
  });

</script>
{% endblock scripts %}

services/templates/services/detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<!-- info página -->
<section class="pagina-info">
  <div class="container">
    <p>{{ service.name }}</p>
  </div>
</section>

<main>
    <div class="container pagina-review">
        <header class="header-servico">
            <div>
                <img src="{{ service.user.profile.avatar.url }}" alt="" width="45px" height="45px" class="user-img">
                <p>{{ service.user.get_full_name }}</p>
            </div>
            <div>
                <img src="{% static "img/star-orange.svg" %}" alt="" width="20px" height="20px">
                <p>{{ service.average_rating}} ({{ service.total_reviews}})</p>
            </div>
        </header>

        <div class="review">
            <div>
                <img src="{{ service.picture.url }}" alt="" width="100%">
                <div class="review-infos">
                    <div id="informacoes" class="infos-paginas active-item">
                        <p>Informações</p>
                    </div>
                    <div id="sobre-profissional" class="infos-paginas ">
                        <p>Sobre o profissional</p>
                    </div>
                    <div id="reviews" class="infos-paginas">
                        <p>Review</p>
                    </div>
                </div>
                <div class="divisor-infos">
                </div>
                <section class="servico-secao servico-informacoes active-servico">
                  {{ service.description|linebreaksbr }}
                </section>

                <section class="servico-secao servico-sobre-profissional">
                    <div class="profissional-titulo">
                        <img src="{{ service.user.profile.avatar.url }}" alt="" width="100px" height="100px"
                            class="foto-usuario">
                        <div class="avaliacao-profissional">
                            <h3>{{ service.user.get_full_name }}</h3>
                            <div class="avaliacao">
                                <img src="{% static "img/star-orange.svg" %}" alt="">
                                {{ service.average_rating}} ({{ service.total_reviews }})
                            </div>
                        </div>
                    </div>

                    <div class="informacoes-profissional">
                        <div class="cidade">
                            <h4>Cidade</h4>
                            <p>{{ service.user.profile.city }}-{{ service.user.profile.region }}</p>
                        </div>
                        <div class="taxa">
                            <h4>Taxa de conclusão do pedido</h4>
                            <p>{{ conclusion_rate }}%</p>
                        </div>
                        <div class="tempo-conta">
                            <h4>Usuário desde</h4>
                            <p>{{ service.user.date_joined.year }}</p>
                        </div>
                        <div class="servicos-realizados">
                            <h4>Serviços realizados</h4>
                            <p>{{ user_done_services }}</p>
                        </div>
                        <div class="info-servicos-profissional">
                            <p>{{ service.user.profile.about|linebreaksbr }}</p>
                        </div>
                    </div>
                </section>

                <section class="servico-secao servico-reviews">
                    {% for review in reviews %}
                        <div class="profissional-titulo review-item">
                            <img src="{% static "img/cleyson-lima.jpg" %}" alt="" width="100px" height="100px"
                                class="foto-usuario">
                            <div class="avaliacao-profissional">
                                <h3>{{ review.order.name }}</h3>
                                <div class="avaliacao">
                                    <img src="{% static "img/star-orange5.svg" %}" alt=""> {{ review.rating }}
                                    <p>{{ review.comment }}</p>
                                </div>
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
                </section>
            </div>

            <aside>
                <div class="aside">
                    <div class="bloco-valor">
                        <div class="aside-titulo">
                            <h3>Nosso pacote</h3>
                            <span>${{ service.price }}</span>
                        </div>
                        <a href="{% url "services:create_order" pk=service.pk %}" class="btn-green">Agendar serviço</a>
                    </div>
                    <div class="info-qtd">
                        <img src="{% static "img/check-fill.svg" %}" alt="">
                        <p>{{ done_services }} serviços realizados</p>
                    </div>
                    <div class="info-aprovacao">
                        <img src="{% static "img/star.svg" %}" alt="">
                        <p>Taxa de aprovação {{ approval_rate }}%</p>
                    </div>
                </div>
            </aside>
        </div>
    </div>
</main>
{% endblock %}

{% block scripts %}
<script>
  const itensPagina = document.querySelectorAll('.infos-paginas');

  itensPagina.forEach((item) => {
      item.addEventListener('click', (event) => {
          event.preventDefault();
          //remove a classe do elemento não clicado
          itensPagina.forEach((el) => el.classList.remove('active-item'));

          //adiciona a classe no elemento clicado
          item.classList.add('active-item');

          // pega o sufixo do item
          const suffixItem = item.getAttribute('id')

          // Seleciona a secao correspondente ao sufixo do elemento clicado
          const secao = document.querySelector(`.servico-${suffixItem}`)
          const secoes = document.querySelectorAll('.servico-secao')

          //remove a classe do elemento não clicado
          secoes.forEach((el) => el.classList.remove('active-servico'));
          secao.classList.add('active-servico')
      });
  });
</script>
{% endblock %}

services/templates/services/list.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<!-- info página -->
<section class="pagina-info">
  <div class="container">
      <p>Nossa lista de melhores serviços</p>
  </div>
</section>

<!-- Busca Serviço -->
<section class="busca">
    <div class="container">
        <div class="busca-item"></div>
    </div>
</section>

<!-- filtro -->
<section class="filtro">
    <div class="container">
        <form class="search-banner" method="get" action="{% url "services:list" %}">
            <select name="city" id="">
                <option value="" selected>Cidade</option>
                {% for city in cities %}
                    <option value="{{ city }}">{{ city }}</option>
                {% endfor %}
            </select>
            <div class="filtro-buttons">
                <div class="search-style">
                    <label for="search">
                        <img src="{% static "img/icon-search.svg" %}" alt="" width="20px">
                    </label>
                    <input type="text" name="q" id="search" placeholder="O que você está procurando...">
                </div>
                <button class="btn-green" type="submit">Buscar</button>
            </div>
        </form>

        <p class="resultado-texto"><span>{{ page.paginator.count }}</span> resultados</p>

        <!-- Serviços -->
        <div class="servicos-grid">
            {% for service in page %}
            <div class="servico-item">
                <img src="{{ service.picture.url }}" alt="" width="100%"
                    class="img-destaque">
                <div class="servico-body">
                    <div class="avatar">
                        <img src="{{ service.user.profile.avatar.url }}" alt="Foto professor" width="45px" class="img-user">
                        <p>{{ service.user.get_full_name }}</p>
                    </div>
                    <h3>{{ service.name }}</h3>
                    <p>{{ service.description }}</p>
                    <a href="" class="servico-link">Iniciando em</a><span> {{ service.price }}</span>
                    <a href="{% url "services:detail" pk=service.pk %}" class="servico-agendar">Ver detalhes</a>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="pagination">
            {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">&#60;</a>
            {% else %}
            <a disabled href="#">&#60;</a>
            {% endif %}
            {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">&#62;</a>
            {% else %}
            <a disabled href="#">&#62;</a>
            {% endif %}
        </div>
    </div>
</section>
{% endblock content %}